name: Deploy website
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
      - name: upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist-files
          path: dist
          # path: | #multiple files can be added like this
          #   dist
          #   package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: get build artifacts
        uses: actions/download-artifact@v3
        with:
          # specifu artifacts identifier other wise do not know which same name we use as ther
          # this download and unzip this artifact
          name: dist-files
      - name: output content
        run: ls

      - name: Deploy
        run: echo "Deploying..."
